### ISSUE TITLE
Native exec driver fails if command to exec is not exists

### ISSUE THREAD

**Issue by samm-git** [samm-git/turris-containers#2]
Docker daemon hangs if it is running with native (`-e native`) driver and client attempts to run non-existing binary.

**Comment by samm-git** [comment]
Backtrace of the failed process:

```
gdb) bt full
#0  0x106d9404 in uw_update_context_1 (context=context@entry=0x583111a8, fs=fs@entry=0x58310ce8)
    at /opt/golang/ct-ng/.build/src/gcc-custom/libgcc/unwind-dw2.c:1432
        orig_context = {reg = {0x0, 0x58310c78, 0x0 <repeats 13 times>, 0x583114ac, 0x583114b0, 0x583114b4, 0x583114b8, 0x583114bc, 0x583114c0,
            0x583114c4, 0x583114c8, 0x583114cc, 0x583114d0, 0x58311f6c, 0x58311f74, 0x58311f7c, 0x58311f84, 0x58311fd4, 0x58311fd8, 0x58311fdc,
            0x0 <repeats 33 times>, 0x58311ff4, 0x0, 0x0, 0x0, 0x0, 0x583114a8, 0x0 <repeats 67 times>, 0x58311f68, 0x58311f70, 0x58311f78, 0x58311f80,
            0x58311f88, 0x58311f90, 0x58311f98, 0x0}, cfa = 0x58311ff0, ra = 0x106e4f58 <makecontext+160>, lsda = 0x0, bases = {tbase = 0x0, dbase = 0x0,
            func = 0x106e4eb8 <makecontext>}, flags = 1073741824, version = 0, args_size = 0, by_value = '\000' <repeats 145 times>}
        cfa = 0x58311ff0
        i = <optimized out>
        tmp_sp = {ptr = 1479614448, word = 1479614448}
#1  0x106d9b14 in uw_update_context (context=context@entry=0x583111a8, fs=fs@entry=0x58310ce8)
    at /opt/golang/ct-ng/.build/src/gcc-custom/libgcc/unwind-dw2.c:1502
No locals.
#2  0x106dab5c in _Unwind_Backtrace (trace=0x10677f18 <unwind>, trace_argument=0x583114f8) at /opt/golang/ct-ng/.build/src/gcc-custom/libgcc/unwind.inc:303
        fs = {regs = {reg = {{loc = {reg = 0, offset = 0, exp = 0x0}, how = REG_UNSAVED} <repeats 146 times>}, prev = 0x0, cfa_offset = 0, cfa_reg = 1,
            cfa_exp = 0x0, cfa_how = CFA_REG_OFFSET}, pc = 0x106e4eb8 <makecontext>, personality = 0x0, data_align = -4, code_align = 4,
          retaddr_column = 65, fde_encoding = 27 '\033', lsda_encoding = 255 '\377', saw_z = 1 '\001', signal_frame = 0 '\000', eh_ptr = 0x0}
        context = {reg = {0x0 <repeats 15 times>, 0x583114ac, 0x583114b0, 0x583114b4, 0x583114b8, 0x583114bc, 0x583114c0, 0x583114c4, 0x583114c8,
            0x583114cc, 0x583114d0, 0x58311f6c, 0x58311f74, 0x58311f7c, 0x58311f84, 0x58311fd4, 0x58311fd8, 0x58311fdc, 0x0 <repeats 33 times>,
            0x58311ff4, 0x0, 0x0, 0x0, 0x0, 0x583114a8, 0x0 <repeats 67 times>, 0x58311f68, 0x58311f70, 0x58311f78, 0x58311f80, 0x58311f88, 0x58311f90,
            0x58311f98, 0x0}, cfa = 0x58311ff0, ra = 0x106e4f58 <makecontext+160>, lsda = 0x0, bases = {tbase = 0x0, dbase = 0x0,
            func = 0x106e4eb8 <makecontext>}, flags = 1073741824, version = 0, args_size = 0, by_value = '\000' <repeats 145 times>}
        code = <optimized out>
#3  0x10678004 in backtrace_full ()
No symbol table info available.
#4  0x1044523c in runtime_callers ()
No symbol table info available.
#5  0x10444cf4 in runtime.Caller ()
No symbol table info available.
#6  0x1018a95c in github_com_docker_libcontainer_stacktrace.Capture (userSkip=1)
---Type <return> to continue, or q <return> to quit---
    at /go/src/github.com/docker/docker/vendor/src/github.com/docker/libcontainer/stacktrace/capture.go:14
        pc = 275664728
        file = {__data = 0x0, __length = 0}
        line = 0
        ok = true
        i = 3595
        skip = 2
        frames = {__values = 0x59310000, __count = 3593, __capacity = 3906}
        $ret0 = {Frames = {__values = 0x0, __count = 0, __capacity = 0}}
#7  0x101725a0 in libcontainer.newSystemError (err=...) at /go/src/github.com/docker/docker/vendor/src/github.com/docker/libcontainer/generic_error.go:48
        gerr = 0x583118a0
        $ret82 = {__methods = 0x0, __object = 0x0}
#8  0x1017129c in libcontainer.$nested4 () at /go/src/github.com/docker/docker/vendor/src/github.com/docker/libcontainer/factory_linux.go:212
        err = {__methods = 0x4, __object = 0x10}
#9  0x1018036c in libcontainer.$thunk9 (__go_thunk_parameter=0x59252030)
    at /go/src/github.com/docker/docker/vendor/src/github.com/docker/libcontainer/factory_linux.go:205
No locals.
#10 0x10445b14 in __go_undefer ()
No symbol table info available.
#11 0x101710cc in github_com_docker_libcontainer.StartInitialization.pN43_github_com_docker_libcontainer.LinuxFactory (l=0x59243ec0, pipefd=3)
    at /go/src/github.com/docker/docker/vendor/src/github.com/docker/libcontainer/factory_linux.go:224
        err = 0x59252010
#12 0x1014bf10 in native.initializer () at /go/src/github.com/docker/docker/daemon/execdriver/native/init.go:35
        err = {__methods = 0x10badae8 <__go_pimt__I5_ErrorFrN6_stringeee__N13_os_exec.Error>, __object = 0x5929cd90}
        factory = {
          __methods = 0x10801b24 <__go_pimt__I6_CreateFpN6_stringpN45_github_com_docker_libcontainer_configs.ConfigerN40_github_com_docker_libcontainer.ContainerN5_erroree4_LoadFpN6_stringerN40_github_com_docker_libcontainer.ContainerN5_erroree19_StartInitializationFpN7_uintptrerN5_erroree4_TypeFrN6_stringeee__N43_github_com_docker_libcontainer.LinuxFactory>, __object = 0x59243ec0}
        err = {__methods = 0x0, __object = 0x0}
#13 0x102ed97c in github_com_docker_docker_pkg_reexec.Init () at /go/src/github.com/docker/docker/pkg/reexec/reexec.go:26
---Type <return> to continue, or q <return> to quit---
        initializer = 0x10bab9b0 <github_com_docker_docker_daemon_execdriver_native.initializer$descriptor>
        exists = true
        $ret1 = false
#14 0x10008900 in main.main () at /go/src/github.com/docker/docker/docker/docker.go:29
        stdin = {__methods = 0xd, __object = 0x5925d910}
        stdout = {__methods = 0x1077e7a8, __object = 0x22}
        stderr = {__methods = 0x59258a10, __object = 0x5}
        protoAddrParts = {__values = 0x59258aa0, __count = 22, __capacity = 0}
        cli = 0x1
        tlsConfig = 0x58311a60
```

**Comment by samm-git** [comment]
Native backtrace:

```
syscall.read
    /opt/golang/ct-ng/.build/powerpc-turris-linux-gnuspe/build/build-cc-final/powerpc-turris-linux-gnuspe/libgo/libcalls.go:838
syscall.Read
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/syscall/syscall_unix.go:188
github_com_go_fsnotify_fsnotify.readEvents.pN39_github_com_go_fsnotify_fsnotify.Watcher
    /go/src/github.com/docker/docker/vendor/src/github.com/go-fsnotify/fsnotify/inotify.go:144
goroutine 16 [chan receive]:
main.mainDaemon
    /go/src/github.com/docker/docker/docker/daemon.go:186
main.main
    /go/src/github.com/docker/docker/docker/docker.go:83
goroutine 17 [syscall]:
    goroutine in C code; stack unavailable
goroutine 18 [finalizer wait]:
goroutine 19 [syscall]:
    goroutine in C code; stack unavailable
created by os_signal..import
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/os/signal/signal_unix.go:25
goroutine 24 [chan receive]:
signal.$nested0
    /go/src/github.com/docker/docker/pkg/signal/trap.go:30
created by github_com_docker_docker_pkg_signal.Trap
    /go/src/github.com/docker/docker/pkg/signal/trap.go:28
goroutine 23 [GC sweep wait]:
goroutine 60 [chan receive]:
github_com_docker_docker_daemon.ContainerAttach.pN38_github_com_docker_docker_daemon.Daemon
    /go/src/github.com/docker/docker/daemon/attach.go:104
github_com_docker_docker_engine.Run.pN35_github_com_docker_docker_engine.Job
    /go/src/github.com/docker/docker/engine/job.go:90
server.postContainersAttach
    /go/src/github.com/docker/docker/api/server/server.go:953
server.$nested2
    /go/src/github.com/docker/docker/api/server/server.go:1289
net_http.ServeHTTP.N20_net_http.HandlerFunc
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/net/http/server.go:1265
github_com_gorilla_mux.ServeHTTP.pN29_github_com_gorilla_mux.Router
    /go/src/github.com/docker/docker/vendor/src/github.com/gorilla/mux/mux.go:98
net_http.ServeHTTP.N22_net_http.serverHandler
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/net/http/server.go:1703
net_http.serve.pN13_net_http.conn
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/net/http/server.go:1204
created by net_http.Serve.pN15_net_http.Server
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/net/http/server.go:1751
goroutine 26 [chan receive]:
github_com_docker_docker_api_server.ServeApi
    /go/src/github.com/docker/docker/api/server/server.go:1607
github_com_docker_docker_engine.Run.pN35_github_com_docker_docker_engine.Job
    /go/src/github.com/docker/docker/engine/job.go:90
main.$nested2
    /go/src/github.com/docker/docker/docker/daemon.go:157
created by main.mainDaemon
    /go/src/github.com/docker/docker/docker/daemon.go:156
goroutine 52 [chan receive]:
database_sql.connectionOpener.pN15_database_sql.DB
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/database/sql/sql.go:589
created by database_sql.Open
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/database/sql/sql.go:452
goroutine 28 [IO wait]:
net.Wait.pN12_net.pollDesc
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/net/fd_poll_runtime.go:84
net.WaitRead.pN12_net.pollDesc
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/net/fd_poll_runtime.go:89
net.accept.pN9_net.netFD
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/net/fd_unix.go:419
net.AcceptUnix.pN16_net.UnixListener
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/net/unixsock_posix.go:282
net.Accept.pN16_net.UnixListener
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/net/unixsock_posix.go:293
github_com_docker_docker_pkg_listenbuffer.Accept.pN57_github_com_docker_docker_pkg_listenbuffer.defaultListener
    /go/src/github.com/docker/docker/pkg/listenbuffer/buffer.go:41
net_http.Serve.pN15_net_http.Server
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/net/http/server.go:1728
github_com_docker_docker_api_server.Serve.pN46_github_com_docker_docker_api_server.HttpServer
    /go/src/github.com/docker/docker/api/server/server.go:50
server.$nested5
    /go/src/github.com/docker/docker/api/server/server.go:1599
created by github_com_docker_docker_api_server.ServeApi
    /go/src/github.com/docker/docker/api/server/server.go:1587
goroutine 53 [chan receive]:
github_com_docker_docker_daemon.run.pN46_github_com_docker_docker_daemon.statsCollector
    /go/src/github.com/docker/docker/daemon/stats_collector.go:79
created by daemon.newStatsCollector
    /go/src/github.com/docker/docker/daemon/stats_collector.go:28
goroutine 55 [select]:
daemon.$nested11
    /go/src/github.com/docker/docker/daemon/daemon.go:433
created by github_com_docker_docker_daemon.setupResolvconfWatcher.pN38_github_com_docker_docker_daemon.Daemon
    /go/src/github.com/docker/docker/daemon/daemon.go:431
goroutine 56 [syscall]:
    goroutine in C code; stack unavailable
goroutine 58 [select]:
github_com_docker_docker_daemon.waitForStart.pN41_github_com_docker_docker_daemon.Container
    /go/src/github.com/docker/docker/daemon/container.go:1417
github_com_docker_docker_daemon.Start.pN41_github_com_docker_docker_daemon.Container
    /go/src/github.com/docker/docker/daemon/container.go:412
github_com_docker_docker_daemon.ContainerStart.pN38_github_com_docker_docker_daemon.Daemon
    /go/src/github.com/docker/docker/daemon/start.go:42
github_com_docker_docker_engine.Run.pN35_github_com_docker_docker_engine.Job
    /go/src/github.com/docker/docker/engine/job.go:90
server.postContainersStart
    /go/src/github.com/docker/docker/api/server/server.go:842
server.$nested2
    /go/src/github.com/docker/docker/api/server/server.go:1289
net_http.ServeHTTP.N20_net_http.HandlerFunc
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/net/http/server.go:1265
github_com_gorilla_mux.ServeHTTP.pN29_github_com_gorilla_mux.Router
    /go/src/github.com/docker/docker/vendor/src/github.com/gorilla/mux/mux.go:98
net_http.ServeHTTP.N22_net_http.serverHandler
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/net/http/server.go:1703
net_http.serve.pN13_net_http.conn
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/net/http/server.go:1204
    :t
created by net_http.Serve.pN15_net_http.Server
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/net/http/server.go:1751
goroutine 62 [IO wait]:
net.Wait.pN12_net.pollDesc
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/net/fd_poll_runtime.go:84
net.WaitRead.pN12_net.pollDesc
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/net/fd_poll_runtime.go:89
net.Read.pN9_net.netFD
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/net/fd_unix.go:242
net.Read.pN8_net.conn
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/net/net.go:121
net.Read.pN12_net.UnixConn
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/net/unixsock_posix.go:103
github_com_docker_docker_engine.Read.pN37_github_com_docker_docker_engine.Input
    /go/src/github.com/docker/docker/engine/streams.go:138
io.Copy
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/io/io.go:362
daemon.$nested0
    /go/src/github.com/docker/docker/daemon/attach.go:93
created by github_com_docker_docker_daemon.ContainerAttach.pN38_github_com_docker_docker_daemon.Daemon
    /go/src/github.com/docker/docker/daemon/attach.go:90
goroutine 63 [semacquire]:
sync.Wait.pN9_sync.Cond
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/sync/cond.go:62
io.read.pN7_io.pipe
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/io/pipe.go:52
io.Read.pN13_io.PipeReader
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/io/pipe.go:134
github_com_docker_docker_pkg_ioutils.drain.pN46_github_com_docker_docker_pkg_ioutils.bufReader
    /go/src/github.com/docker/docker/pkg/ioutils/readers.go:114
created by github_com_docker_docker_pkg_ioutils.NewBufReader
    /go/src/github.com/docker/docker/pkg/ioutils/readers.go:84
goroutine 64 [semacquire]:
sync.Wait.pN9_sync.Cond
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/sync/cond.go:62
io.read.pN7_io.pipe
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/io/pipe.go:52
io.Read.pN13_io.PipeReader
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/io/pipe.go:134
github_com_docker_docker_pkg_ioutils.drain.pN46_github_com_docker_docker_pkg_ioutils.bufReader
    /go/src/github.com/docker/docker/pkg/ioutils/readers.go:114
created by github_com_docker_docker_pkg_ioutils.NewBufReader
    /go/src/github.com/docker/docker/pkg/ioutils/readers.go:84
goroutine 65 [semacquire]:
sync.Wait.pN9_sync.Cond
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/sync/cond.go:62
io.read.pN7_io.pipe
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/io/pipe.go:52
io.Read.pN13_io.PipeReader
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/io/pipe.go:134
github_com_docker_docker_utils.CopyEscapable
    /go/src/github.com/docker/docker/utils/utils.go:178
daemon.$nested1
    /go/src/github.com/docker/docker/daemon/attach.go:161
created by github_com_docker_docker_daemon.Attach.pN38_github_com_docker_docker_daemon.Daemon
    /go/src/github.com/docker/docker/daemon/attach.go:138
goroutine 66 [semacquire]:
sync.Wait.pN9_sync.Cond
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/sync/cond.go:62
github_com_docker_docker_pkg_ioutils.Read.pN46_github_com_docker_docker_pkg_ioutils.bufReader
    /go/src/github.com/docker/docker/pkg/ioutils/readers.go:207
io.Copy
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/io/io.go:362
daemon.$nested3
    /go/src/github.com/docker/docker/daemon/attach.go:191
created by github_com_docker_docker_daemon.Attach.pN38_github_com_docker_docker_daemon.Daemon
    /go/src/github.com/docker/docker/daemon/attach.go:201
goroutine 67 [semacquire]:
sync.Wait.pN9_sync.Cond
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/sync/cond.go:62
github_com_docker_docker_pkg_ioutils.Read.pN46_github_com_docker_docker_pkg_ioutils.bufReader
    /go/src/github.com/docker/docker/pkg/ioutils/readers.go:207
io.Copy
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/io/io.go:362
daemon.$nested3
    /go/src/github.com/docker/docker/daemon/attach.go:191
created by github_com_docker_docker_daemon.Attach.pN38_github_com_docker_docker_daemon.Daemon
    /go/src/github.com/docker/docker/daemon/attach.go:202
goroutine 68 [semacquire]:
sync.Wait.pN14_sync.WaitGroup
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/sync/waitgroup.go:132
daemon.$nested5
    /go/src/github.com/docker/docker/daemon/attach.go:205
promise.$nested0
    /go/src/github.com/docker/docker/pkg/promise/promise.go:8
created by github_com_docker_docker_pkg_promise.Go
    /go/src/github.com/docker/docker/pkg/promise/promise.go:7
goroutine 70 [syscall]:
    goroutine in C code; stack unavailable
created by github_com_docker_docker_pkg_promise.Go
    /go/src/github.com/docker/docker/pkg/promise/promise.go:7
goroutine 71 [semacquire]:
sync.Wait.pN9_sync.Cond
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/sync/cond.go:62
io.read.pN7_io.pipe
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/io/pipe.go:52
io.Read.pN13_io.PipeReader
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/io/pipe.go:134
github_com_docker_docker_pkg_ioutils.drain.pN46_github_com_docker_docker_pkg_ioutils.bufReader
    /go/src/github.com/docker/docker/pkg/ioutils/readers.go:114
created by github_com_docker_docker_pkg_ioutils.NewBufReader
    /go/src/github.com/docker/docker/pkg/ioutils/readers.go:84
goroutine 72 [semacquire]:
sync.Wait.pN9_sync.Cond
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/sync/cond.go:62
io.read.pN7_io.pipe
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/io/pipe.go:52
io.Read.pN13_io.PipeReader
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/io/pipe.go:134
github_com_docker_docker_pkg_ioutils.drain.pN46_github_com_docker_docker_pkg_ioutils.bufReader
    /go/src/github.com/docker/docker/pkg/ioutils/readers.go:114
created by github_com_docker_docker_pkg_ioutils.NewBufReader
    /go/src/github.com/docker/docker/pkg/ioutils/readers.go:84
goroutine 73 [semacquire]:
sync.Wait.pN9_sync.Cond
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/sync/cond.go:62
github_com_docker_docker_pkg_ioutils.Read.pN46_github_com_docker_docker_pkg_ioutils.bufReader
    /go/src/github.com/docker/docker/pkg/ioutils/readers.go:207
bufio.Scan.pN13_bufio.Scanner
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/bufio/scan.go:180
github_com_docker_docker_daemon_logger.copySrc.pN45_github_com_docker_docker_daemon_logger.Copier
    /go/src/github.com/docker/docker/daemon/logger/copier.go:44
created by github_com_docker_docker_daemon_logger.Run.pN45_github_com_docker_docker_daemon_logger.Copier
    /go/src/github.com/docker/docker/daemon/logger/copier.go:37
goroutine 74 [semacquire]:
sync.Wait.pN9_sync.Cond
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/sync/cond.go:62
github_com_docker_docker_pkg_ioutils.Read.pN46_github_com_docker_docker_pkg_ioutils.bufReader
    /go/src/github.com/docker/docker/pkg/ioutils/readers.go:207
bufio.Scan.pN13_bufio.Scanner
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/bufio/scan.go:180
github_com_docker_docker_daemon_logger.copySrc.pN45_github_com_docker_docker_daemon_logger.Copier
    /go/src/github.com/docker/docker/daemon/logger/copier.go:44
created by github_com_docker_docker_daemon_logger.Run.pN45_github_com_docker_docker_daemon_logger.Copier
    /go/src/github.com/docker/docker/daemon/logger/copier.go:37
goroutine 78 [running]:
    goroutine running on other thread; stack unavailable
created by signal.$nested0
    /go/src/github.com/docker/docker/pkg/signal/trap.go:31
goroutine 76 [syscall]:
    goroutine in C code; stack unavailable
created by github_com_docker_docker_daemon_execdriver_native.AttachPipes.pN60_github_com_docker_docker_daemon_execdriver_native.TtyConsole
    /go/src/github.com/docker/docker/daemon/execdriver/native/driver.go:398
goroutine 77 [semacquire]:
sync.Wait.pN9_sync.Cond
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/sync/cond.go:62
io.read.pN7_io.pipe
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/io/pipe.go:52
io.Read.pN13_io.PipeReader
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/io/pipe.go:134
io.Copy
    /opt/golang/ct-ng/.build/src/gcc-custom/libgo/go/io/io.go:362
native.$nested4
    /go/src/github.com/docker/docker/daemon/execdriver/native/driver.go:410
created by github_com_docker_docker_daemon_execdriver_native.AttachPipes.pN60_github_com_docker_docker_daemon_execdriver_native.TtyConsole
    /go/src/github.com/docker/docker/daemon/execdriver/native/driver.go:409
```
